"""add_audit_logs_and_qvpn_alerts

Revision ID: 0d936d7cfb67
Revises: a3f1c9e2b847
Create Date: 2026-06-25 19:09:21.528314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d936d7cfb67'
down_revision: Union[str, Sequence[str], None] = 'a3f1c9e2b847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_client_id', 'audit_logs', ['client_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_path', 'audit_logs', ['path'], unique=False)
    op.create_index('ix_audit_logs_status_code', 'audit_logs', ['status_code'], unique=False)
    op.alter_column('api_keys', 'scopes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('qvpn_alerts', 'severity',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('qvpn_alerts', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('qvpn_alerts', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('ix_qvpn_alerts_client_id_timestamp', 'qvpn_alerts', ['client_id', 'timestamp'], unique=False)
    op.drop_constraint(op.f('qvpn_alerts_client_id_fkey'), 'qvpn_alerts', type_='foreignkey')
    op.create_foreign_key(None, 'qvpn_alerts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qvpn_alerts', type_='foreignkey')
    op.create_foreign_key(op.f('qvpn_alerts_client_id_fkey'), 'qvpn_alerts', 'clients', ['client_id'], ['id'])
    op.drop_index('ix_qvpn_alerts_client_id_timestamp', table_name='qvpn_alerts')
    op.alter_column('qvpn_alerts', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('qvpn_alerts', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('qvpn_alerts', 'severity',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('api_keys', 'scopes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_audit_logs_status_code', table_name='audit_logs')
    op.drop_index('ix_audit_logs_path', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_client_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
