"""add api_keys table

Revision ID: 559ff94c3da4
Revises: 
Create Date: 2026-06-20 19:55:44.347513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '559ff94c3da4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=False),
    sa.Column('hashed_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=True)
    op.create_index('ix_api_keys_lookup', 'api_keys', ['key_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_table('tunnel_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tunnel_events_event_type', 'tunnel_events', ['event_type'], unique=False)
    op.create_index('ix_tunnel_events_occurred_at', 'tunnel_events', ['occurred_at'], unique=False)
    op.create_index('ix_tunnel_events_session_id', 'tunnel_events', ['session_id'], unique=False)
    op.drop_table('system_metrics')
    op.drop_table('security_alerts')
    op.drop_table('ip_history')
    op.drop_table('user_activities')
    op.drop_table('ip_change_logs')
    op.drop_table('process_events')
    op.drop_table('security_events')
    op.drop_table('process_metrics')
    op.drop_table('usb_events')
    op.drop_table('network_activities')
    op.drop_table('vpn_events')
    op.drop_table('endpoints')
    op.drop_table('threat_rules')
    op.add_column('clients', sa.Column('pqc_key_id', sa.Text(), nullable=True))
    op.create_index('ix_clients_client_identifier', 'clients', ['client_identifier'], unique=False)
    op.create_index('ix_clients_is_active', 'clients', ['is_active'], unique=False)
    op.add_column('sessions', sa.Column('pqc_key_id', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('tunnel_status', sa.Text(), server_default='CONNECTING', nullable=False))
    op.add_column('sessions', sa.Column('established_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_sessions_client_id', 'sessions', ['client_id'], unique=False)
    op.create_index('ix_sessions_created_at', 'sessions', ['created_at'], unique=False)
    op.create_index('ix_sessions_kem_state', 'sessions', ['kem_state'], unique=False)
    op.create_index('ix_sessions_tunnel_status', 'sessions', ['tunnel_status'], unique=False)
    op.create_index('ix_traffic_stats_recorded_at', 'traffic_stats', ['recorded_at'], unique=False)
    op.create_index('ix_traffic_stats_session_id', 'traffic_stats', ['session_id'], unique=False)
    op.create_index('ix_tunnel_states_last_heartbeat', 'tunnel_states', ['last_heartbeat'], unique=False)
    op.create_index('ix_tunnel_states_session_id', 'tunnel_states', ['session_id'], unique=False)
    op.create_index('ix_tunnel_states_status', 'tunnel_states', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tunnel_states_status', table_name='tunnel_states')
    op.drop_index('ix_tunnel_states_session_id', table_name='tunnel_states')
    op.drop_index('ix_tunnel_states_last_heartbeat', table_name='tunnel_states')
    op.drop_index('ix_traffic_stats_session_id', table_name='traffic_stats')
    op.drop_index('ix_traffic_stats_recorded_at', table_name='traffic_stats')
    op.drop_index('ix_sessions_tunnel_status', table_name='sessions')
    op.drop_index('ix_sessions_kem_state', table_name='sessions')
    op.drop_index('ix_sessions_created_at', table_name='sessions')
    op.drop_index('ix_sessions_client_id', table_name='sessions')
    op.drop_column('sessions', 'closed_at')
    op.drop_column('sessions', 'established_at')
    op.drop_column('sessions', 'tunnel_status')
    op.drop_column('sessions', 'pqc_key_id')
    op.drop_index('ix_clients_is_active', table_name='clients')
    op.drop_index('ix_clients_client_identifier', table_name='clients')
    op.drop_column('clients', 'pqc_key_id')
    op.create_table('threat_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('threat_rules_pkey'))
    )
    op.create_table('endpoints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hostname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('os_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('agent_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('endpoints_pkey'))
    )
    op.create_table('vpn_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vpn_events_pkey'))
    )
    op.create_table('network_activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('local_port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remote_ip', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('remote_port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('network_activities_pkey'))
    )
    op.create_table('usb_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('usb_events_endpoint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usb_events_pkey'))
    )
    op.create_table('process_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cpu_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('process_metrics_pkey'))
    )
    op.create_table('security_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source_module', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('security_events_endpoint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('security_events_pkey'))
    )
    op.create_table('process_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('process_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('process_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_pid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hash_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('process_events_endpoint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('process_events_pkey'))
    )
    op.create_table('ip_change_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('new_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('change_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('ip_change_logs_endpoint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ip_change_logs_pkey'))
    )
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_generated', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('record_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_activities_pkey'))
    )
    op.create_table('ip_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ip_history_pkey'))
    )
    op.create_table('security_alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'OPEN'::text"), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('security_alerts_pkey'))
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ram_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('disk_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('system_metrics_pkey'))
    )
    op.drop_index('ix_tunnel_events_session_id', table_name='tunnel_events')
    op.drop_index('ix_tunnel_events_occurred_at', table_name='tunnel_events')
    op.drop_index('ix_tunnel_events_event_type', table_name='tunnel_events')
    op.drop_table('tunnel_events')
    op.drop_index('ix_api_keys_lookup', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
