"""
routes/alerts.py — Security alert ingestion and management endpoints.

  POST   /api/v1/alerts              — Ingest one alert from the client agent
  GET    /api/v1/alerts              — List all alerts (filterable)
  GET    /api/v1/alerts/{alert_id}   — Get a single alert
  PATCH  /api/v1/alerts/{alert_id}   — Update alert status (acknowledge / resolve)
  GET    /api/v1/clients/{client_id}/alerts — All alerts for one client
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session as DBSession

from app.core.database import get_db
from app.models.qvpn_alert import QVPNAlert
from app.services import alert_service

logger = logging.getLogger("qvpn.routes.alerts")

router = APIRouter(tags=["Security Alerts"])


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------

class AlertIngestRequest(BaseModel):
    alert_id:    str = Field(..., description="UUID generated by the client agent")
    client_id:   str = Field(..., description="CLIENT_IDENTIFIER or raw UUID")
    timestamp:   Optional[str] = None
    severity:    str = Field(..., description="LOW | MEDIUM | HIGH | CRITICAL")
    description: str
    status:      Optional[str] = "open"


class AlertStatusPatch(BaseModel):
    status: str = Field(..., description="open | acknowledged | resolved | suppressed")


class AlertOut(BaseModel):
    alert_id:    str
    client_id:   str
    timestamp:   datetime
    severity:    str
    description: str
    status:      Optional[str]

    model_config = {"from_attributes": True}


def _to_out(row: QVPNAlert) -> AlertOut:
    return AlertOut(
        alert_id    = str(row.alert_id),
        client_id   = str(row.client_id),
        timestamp   = row.timestamp,
        severity    = row.severity,
        description = row.description,
        status      = row.status,
    )


# ---------------------------------------------------------------------------
# Ingestion
# ---------------------------------------------------------------------------

@router.post(
    "/alerts",
    response_model=AlertOut,
    status_code=201,
    summary="Ingest a security alert from the client agent",
    description=(
        "Receives a single SecurityAlert emitted by the embedded agent. "
        "client_id may be a CLIENT_IDENTIFIER string or a raw UUID — the gateway "
        "resolves it to the FK before inserting. Severity must be LOW/MEDIUM/HIGH/CRITICAL."
    ),
)
def ingest_alert(
    payload: AlertIngestRequest,
    db: DBSession = Depends(get_db),
):
    try:
        row = alert_service.ingest_alert(db, payload.model_dump())
    except ValueError as exc:
        msg = str(exc)
        if "not found" in msg or "inactive" in msg.lower():
            raise HTTPException(status_code=401, detail=msg)
        raise HTTPException(status_code=422, detail=msg)
    return _to_out(row)


# ---------------------------------------------------------------------------
# Query — all alerts (admin view)
# ---------------------------------------------------------------------------

@router.get(
    "/alerts",
    response_model=List[AlertOut],
    summary="List security alerts",
    description="Returns alerts across all clients. Filterable by severity, status, since.",
)
def list_alerts(
    severity: Optional[str] = Query(None, description="LOW | MEDIUM | HIGH | CRITICAL"),
    status:   Optional[str] = Query(None, description="open | acknowledged | resolved | suppressed"),
    since:    Optional[datetime] = Query(None, description="Return alerts after this ISO timestamp"),
    limit:    int = Query(100, ge=1, le=1000),
    db:       DBSession = Depends(get_db),
):
    rows = alert_service.list_alerts(
        db, severity=severity, status=status, since=since, limit=limit
    )
    return [_to_out(r) for r in rows]


# ---------------------------------------------------------------------------
# Query — per client
# ---------------------------------------------------------------------------

@router.get(
    "/clients/{client_id}/alerts",
    response_model=List[AlertOut],
    summary="Query security alerts for a specific client",
)
def get_client_alerts(
    client_id: str,
    severity: Optional[str] = Query(None),
    status:   Optional[str] = Query(None),
    since:    Optional[datetime] = Query(None),
    limit:    int = Query(100, ge=1, le=1000),
    db:       DBSession = Depends(get_db),
):
    try:
        uuid.UUID(client_id)
    except ValueError:
        raise HTTPException(status_code=422, detail="client_id must be a valid UUID")

    rows = alert_service.list_alerts(
        db, client_id=client_id, severity=severity, status=status, since=since, limit=limit
    )
    return [_to_out(r) for r in rows]


# ---------------------------------------------------------------------------
# Single alert
# ---------------------------------------------------------------------------

@router.get(
    "/alerts/{alert_id}",
    response_model=AlertOut,
    summary="Get a single security alert",
)
def get_alert(alert_id: str, db: DBSession = Depends(get_db)):
    try:
        alert_uuid = uuid.UUID(alert_id)
    except ValueError:
        raise HTTPException(status_code=422, detail="alert_id must be a valid UUID")

    row = db.query(QVPNAlert).filter(QVPNAlert.alert_id == alert_uuid).first()
    if not row:
        raise HTTPException(status_code=404, detail=f"Alert {alert_id!r} not found")
    return _to_out(row)


# ---------------------------------------------------------------------------
# Status update
# ---------------------------------------------------------------------------

@router.patch(
    "/alerts/{alert_id}",
    response_model=AlertOut,
    summary="Update alert status",
    description="Transition an alert to acknowledged, resolved, or suppressed.",
)
def patch_alert_status(
    alert_id: str,
    payload:  AlertStatusPatch,
    db:       DBSession = Depends(get_db),
):
    try:
        row = alert_service.update_alert_status(db, alert_id, payload.status)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc))

    if not row:
        raise HTTPException(status_code=404, detail=f"Alert {alert_id!r} not found")
    return _to_out(row)
